version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: 1234
      PGHOST: db
      PGDATABASE: postgres
    depends_on:
      - db
    ports:
      - 80:80

  db:
    image: postgres
    volumes:
      - ./.data:/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      PGDATA: /var/app/data
