version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: 1234
      PG_HOST: db
      PG_DB: postgres
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./.data:/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      PGDATA: /var/app/data
