openapi: "3.0.0"
info:
  version: 1.0.0
  title: CsvUpload
paths:
  /upload/{table_name}:
    post:
      summary: post CSV
      parameters:
      - name: table_name
        in: path
        description: Table name
        required: true
        schema:
          type: string
          format: string
      responses:
        '200':
          description: Cvs load success
      requestBody:
        content:
          text/csv:
            schema:
              type: string
              format: csv
          application/octet-stream:
            schema:
              type: string
              format: binary
